import { del, get, post, put } from 'aws-amplify/api';
// Import from aws package - amplify_outputs.json is generated there
import amplifyOutputs from '../../aws/amplify_outputs.json';

/**
 * AWS Amplify API Factory
 *
 * Wrapper around aws-amplify/api that provides type-safe HTTP methods.
 *
 * Authentication:
 * - Uses Cognito credentials automatically (from current user session)
 * - Requests include Authorization header with JWT token
 * - Server validates token via API Gateway IAM policy
 *
 * API Configuration:
 * - API name is loaded from amplify_outputs.json (generated by backend.ts)
 * - No hardcoding required - adapts to sandbox/production automatically
 *
 * Usage:
 * const api = AwsAmplifyApiFactory.getInstance();
 * const response = await api.get('/account/123').response;
 * const data = await response.body.json();
 */
export class AwsAmplifyApiFactory {
  private static _instance: AwsAmplifyApiFactory;
  private _apiName: string;

  private constructor() {
    // Get API name from amplify_outputs.json
    const customOutputs = amplifyOutputs as any;
    if (!customOutputs.custom?.API) {
      throw new Error(
        'REST API not configured in amplify_outputs.json. Ensure backend exports API config and app calls NueInkAmplifyBuilder.builder().withApiSupport().build()'
      );
    }

    // Get first API name from custom.API object
    const apiNames = Object.keys(customOutputs.custom.API);
    if (apiNames.length === 0) {
      throw new Error('No REST API found in amplify_outputs.json');
    }

    this._apiName = apiNames[0];
    console.log(`[AwsAmplifyApiFactory] Using REST API: ${this._apiName}`);
  }

  public static getInstance() {
    if (!this._instance) {
      this._instance = new AwsAmplifyApiFactory();
    }
    return this._instance;
  }

  private get apiConfig() {
    return {
      apiName: this._apiName,
      options: {
        retryStrategy: {
          strategy: 'no-retry' as const,
        },
      },
    };
  }

  /**
   * GET request with automatic Cognito auth
   */
  public get = (path: string) => {
    return get({ ...this.apiConfig, path });
  };

  /**
   * POST request with automatic Cognito auth
   */
  public post = <T = any>(path: string, body?: T) => {
    return post({
      ...this.apiConfig,
      path,
      options: {
        ...this.apiConfig.options,
        body,
      },
    });
  };

  /**
   * PUT request with automatic Cognito auth
   */
  public put = <T = any>(path: string, body?: T) => {
    return put({
      ...this.apiConfig,
      path,
      options: {
        ...this.apiConfig.options,
        body,
      },
    });
  };

  /**
   * DELETE request with automatic Cognito auth
   */
  public del = (path: string) => {
    return del({ ...this.apiConfig, path });
  };
}
